# Generated by Django 4.1.5 on 2023-01-09 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 1, 9, 8, 8, 43, 431988)),
        ),
    ]
