# Generated by Django 4.1.3 on 2023-01-09 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 1, 9, 9, 49, 37, 399721)),
        ),
    ]
